### ISSUE TITLE
IPv6 issues

### ISSUE THREAD

**Issue by Benchwork** [Athlon1600/php-proxy-installer#1]
when installing on a new system, it took over an hour to run because each get action was super slow. and then I got this

```
All settings correct for using Composer
Downloading...
Download failed: file_get_contents(https://getcomposer.org/composer.phar.sig): failed to open stream: Connection timed out
Download failed: file_get_contents(https://getcomposer.org/composer.phar.sig): failed to open stream: Connection timed out
file_get_contents(https://getcomposer.org/composer.phar): failed to open stream: Connection timed out
The download failed repeatedly, aborting.
Writing to a configuration file /etc/apache2/sites-available/php_proxy.conf...
Enabling site php_proxy.
To activate the new configuration, you need to run:
  service apache2 reload
[ ok ] Restarting web server: apache2.
/dev/fd/63: line 145: /usr/local/bin/composer: Permission denied
/dev/fd/63: line 148: /usr/local/bin/composer: Permission denied
no crontab for root
```

with a quick search I found this [(https://github.com/composer/composer/issues/4142#issuecomment-117648869)]  could this be added to the script?

ran `sh -c "echo 'precedence ::ffff:0:0/96 100' >> /etc/gai.conf"`
but am unable to rerun the script to test because `Apache2 is already installed on this system. This installation only works on fresh systems
` is there a way to add a switch to override and run anyway?

**Comment by Athlon1600** [comment]
Just do:

```
rm -rf /etc/apache2/*
```

before running php-proxy-installer script and it will let you install it then
