### ISSUE TITLE
Server Configuration

### ISSUE THREAD

**Issue by Bytepie** [Athlon1600/php-proxy-installer#5]
What is the best server configuration for nginx/apache for running php-proxy. I use digital ocean. What kind of VPS is best for it and what should be the nginx/apache workers should it have. Any idea what is estimated number of users it can handle at any given time.

I have tried apache it ran out of memory pretty quick with 1gb vps with only 7 - 15 users any given time.

**Comment by ch4rc0al1080** [comment]
I use swap.
It works well

**Comment by Bytepie** [comment]
> I use swap.
> It works well

Yes I also started using it eventually, though not ideal as ram but rather avoid pay extra bucks.
